name: 'Build and Push Docker Image'
description: 'Builds a Docker image and pushes it to Docker Hub.'
branding:
  icon: 'package' # 或其他适合 Docker 主题的 Feather icon
  color: 'blue' # 指定蓝色作为图标颜色
inputs:
  docker_hub_username:
    description: 'Docker Hub username'
    required: true
  docker_hub_access_token:
    description: 'Docker Hub access token'
    required: true
  image_name:
    description: 'The name of the image to build and push'
    required: true
runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_hub_username }}
        password: ${{ inputs.docker_hub_access_token }}
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ inputs.image_name }}
